Plugin: fix link error on missing gobject.
When linking Plugin, I got this error on CYGWIN:

[ 97%] Linking CXX shared library ../bin/cygplugin.dll
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/plugin.dir/GTKNotebook.cpp.o:GTKNotebook.cp:(.text+0x1ed8): undefined reference to `g_type_check_instance_cast'
/usr/lib/gcc/x86_64-pc-cygwin/11/../../../../x86_64-pc-cygwin/bin/ld: CMakeFiles/plugin.dir/GTKNotebook.cpp.o:GTKNotebook.cp:(.text+0x1f02): undefined reference to `g_signal_connect_data'

It seems that under some platforms Plugin could require the presence of gobject when linking, so I used the same solution implemented into LiteEditor:

https://github.com/eranif/codelite/blob/0035da6868021652fe633b04bf184b49001a94e7/LiteEditor/CMakeLists.txt#L65

after that, Plugin links as expected.